package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePoItem<M extends BasePoItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}
	
	public java.lang.String getOrderNum() {
		return getStr("orderNum");
	}

	/**
	 * 收货单号
	 */
	public void setIbOrderNum(java.lang.String ibOrderNum) {
		set("ibOrderNum", ibOrderNum);
	}
	
	/**
	 * 收货单号
	 */
	public java.lang.String getIbOrderNum() {
		return getStr("ibOrderNum");
	}

	public void setIbOrderLine(java.lang.String ibOrderLine) {
		set("ibOrderLine", ibOrderLine);
	}
	
	public java.lang.String getIbOrderLine() {
		return getStr("ibOrderLine");
	}

	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	public java.lang.String getMaterial() {
		return getStr("material");
	}

	public void setIbDate(java.lang.String ibDate) {
		set("ibDate", ibDate);
	}
	
	public java.lang.String getIbDate() {
		return getStr("ibDate");
	}

	public void setReceivedQuantity(java.math.BigDecimal receivedQuantity) {
		set("receivedQuantity", receivedQuantity);
	}
	
	public java.math.BigDecimal getReceivedQuantity() {
		return get("receivedQuantity");
	}

	public void setIndicator10(java.lang.String indicator10) {
		set("indicator10", indicator10);
	}
	
	public java.lang.String getIndicator10() {
		return getStr("indicator10");
	}

	public void setUnitCost10(java.math.BigDecimal unitCost10) {
		set("unitCost10", unitCost10);
	}
	
	public java.math.BigDecimal getUnitCost10() {
		return get("unitCost10");
	}

	public void setIndicator20(java.lang.String Indicator20) {
		set("Indicator20", Indicator20);
	}
	
	public java.lang.String getIndicator20() {
		return getStr("Indicator20");
	}

	public void setTotalAmt10(java.math.BigDecimal totalAmt10) {
		set("totalAmt10", totalAmt10);
	}
	
	public java.math.BigDecimal getTotalAmt10() {
		return get("totalAmt10");
	}

	public void setCompareAmt(java.math.BigDecimal compareAmt) {
		set("compareAmt", compareAmt);
	}
	
	public java.math.BigDecimal getCompareAmt() {
		return get("compareAmt");
	}

	public void setDiffAmt(java.math.BigDecimal diffAmt) {
		set("diffAmt", diffAmt);
	}
	
	public java.math.BigDecimal getDiffAmt() {
		return get("diffAmt");
	}

	public void setPickupOrderNum(java.lang.String pickupOrderNum) {
		set("pickupOrderNum", pickupOrderNum);
	}
	
	public java.lang.String getPickupOrderNum() {
		return getStr("pickupOrderNum");
	}

	public void setPickupOrderLine(java.lang.String pickupOrderLine) {
		set("pickupOrderLine", pickupOrderLine);
	}
	
	public java.lang.String getPickupOrderLine() {
		return getStr("pickupOrderLine");
	}

	public void setPickupDate(java.lang.String pickupDate) {
		set("pickupDate", pickupDate);
	}
	
	public java.lang.String getPickupDate() {
		return getStr("pickupDate");
	}

	public void setPickupQuantity(java.math.BigDecimal pickupQuantity) {
		set("pickupQuantity", pickupQuantity);
	}
	
	public java.math.BigDecimal getPickupQuantity() {
		return get("pickupQuantity");
	}

	public void setUnitCost20(java.math.BigDecimal unitCost20) {
		set("unitCost20", unitCost20);
	}
	
	public java.math.BigDecimal getUnitCost20() {
		return get("unitCost20");
	}

	public void setTotalAmt20(java.math.BigDecimal totalAmt20) {
		set("totalAmt20", totalAmt20);
	}
	
	public java.math.BigDecimal getTotalAmt20() {
		return get("totalAmt20");
	}

	public void setFromCurrency(java.lang.String fromCurrency) {
		set("fromCurrency", fromCurrency);
	}
	
	public java.lang.String getFromCurrency() {
		return getStr("fromCurrency");
	}

	public void setFromAmt(java.math.BigDecimal fromAmt) {
		set("fromAmt", fromAmt);
	}
	
	public java.math.BigDecimal getFromAmt() {
		return get("fromAmt");
	}

	public void setToCurrency(java.lang.String toCurrency) {
		set("toCurrency", toCurrency);
	}
	
	public java.lang.String getToCurrency() {
		return getStr("toCurrency");
	}

	public void setToAmt(java.math.BigDecimal toAmt) {
		set("toAmt", toAmt);
	}
	
	public java.math.BigDecimal getToAmt() {
		return get("toAmt");
	}

}
