package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWkInstanceStep<M extends BaseWkInstanceStep<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInstanceID(java.lang.String instanceID) {
		set("instanceID", instanceID);
	}
	
	public java.lang.String getInstanceID() {
		return getStr("instanceID");
	}

	public void setSeqNo(java.lang.String seqNo) {
		set("seqNo", seqNo);
	}
	
	public java.lang.String getSeqNo() {
		return getStr("seqNo");
	}

	public void setStartTime(java.lang.String startTime) {
		set("startTime", startTime);
	}
	
	public java.lang.String getStartTime() {
		return getStr("startTime");
	}

	public void setApprover(java.lang.String approver) {
		set("approver", approver);
	}
	
	public java.lang.String getApprover() {
		return getStr("approver");
	}

	public void setEndTime(java.lang.String endTime) {
		set("endTime", endTime);
	}
	
	public java.lang.String getEndTime() {
		return getStr("endTime");
	}

	public void setApproverComment(java.lang.String approverComment) {
		set("approverComment", approverComment);
	}
	
	public java.lang.String getApproverComment() {
		return getStr("approverComment");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
