package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUtEntry<M extends BaseUtEntry<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setBizDate(java.lang.String bizDate) {
		set("bizDate", bizDate);
	}
	
	public java.lang.String getBizDate() {
		return getStr("bizDate");
	}

	public void setProjectCode(java.lang.String projectCode) {
		set("projectCode", projectCode);
	}
	
	public java.lang.String getProjectCode() {
		return getStr("projectCode");
	}

	public void setClaimHours(java.math.BigDecimal claimHours) {
		set("claimHours", claimHours);
	}
	
	public java.math.BigDecimal getClaimHours() {
		return get("claimHours");
	}

	public void setOnSite(java.lang.String onSite) {
		set("onSite", onSite);
	}
	
	public java.lang.String getOnSite() {
		return getStr("onSite");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setDetails(java.lang.String details) {
		set("details", details);
	}
	
	public java.lang.String getDetails() {
		return getStr("details");
	}

	public void setUpdateDate(java.lang.String updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.lang.String getUpdateDate() {
		return getStr("updateDate");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("updateUser", updateUser);
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("updateUser");
	}

}
