package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegionSales<M extends BaseRegionSales<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}
	
	public java.lang.String getRegion() {
		return getStr("region");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}
	
	public java.lang.String getYear() {
		return getStr("year");
	}

	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}

	public void setBatch(java.lang.String batch) {
		set("batch", batch);
	}
	
	public java.lang.String getBatch() {
		return getStr("batch");
	}

}
