package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePoHead<M extends BasePoHead<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}
	
	public java.lang.String getOrderNum() {
		return getStr("orderNum");
	}

	public void setVendorCode(java.lang.String vendorCode) {
		set("vendorCode", vendorCode);
	}
	
	public java.lang.String getVendorCode() {
		return getStr("vendorCode");
	}

	public void setVendorName(java.lang.String vendorName) {
		set("vendorName", vendorName);
	}
	
	public java.lang.String getVendorName() {
		return getStr("vendorName");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setBatch(java.lang.String batch) {
		set("batch", batch);
	}
	
	public java.lang.String getBatch() {
		return getStr("batch");
	}

	public void setOrderDate(java.lang.String orderDate) {
		set("orderDate", orderDate);
	}
	
	public java.lang.String getOrderDate() {
		return getStr("orderDate");
	}

	public void setItemCount(java.lang.Integer itemCount) {
		set("itemCount", itemCount);
	}
	
	public java.lang.Integer getItemCount() {
		return getInt("itemCount");
	}

	public void setTotalAmt(java.math.BigDecimal totalAmt) {
		set("totalAmt", totalAmt);
	}
	
	public java.math.BigDecimal getTotalAmt() {
		return get("totalAmt");
	}

	public void setOrderDateStr(java.lang.String orderDateStr) {
		set("orderDateStr", orderDateStr);
	}
	
	public java.lang.String getOrderDateStr() {
		return getStr("orderDateStr");
	}

	public void setOrderMonth(java.lang.String orderMonth) {
		set("orderMonth", orderMonth);
	}
	
	public java.lang.String getOrderMonth() {
		return getStr("orderMonth");
	}

	public void setPlantInd(java.lang.String plantInd) {
		set("plantInd", plantInd);
	}
	
	public java.lang.String getPlantInd() {
		return getStr("plantInd");
	}

	public void setPlantName(java.lang.String plantName) {
		set("plantName", plantName);
	}
	
	public java.lang.String getPlantName() {
		return getStr("plantName");
	}

}
