package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWkInstance<M extends BaseWkInstance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setBizUnit(java.lang.String bizUnit) {
		set("bizUnit", bizUnit);
	}
	
	public java.lang.String getBizUnit() {
		return getStr("bizUnit");
	}

	public void setBizNum(java.lang.String bizNum) {
		set("bizNum", bizNum);
	}
	
	public java.lang.String getBizNum() {
		return getStr("bizNum");
	}

	public void setProjectCode(java.lang.String projectCode) {
		set("projectCode", projectCode);
	}
	
	public java.lang.String getProjectCode() {
		return getStr("projectCode");
	}

	public void setActionKey(java.lang.String actionKey) {
		set("actionKey", actionKey);
	}
	
	public java.lang.String getActionKey() {
		return getStr("actionKey");
	}

	public void setSeqNo(java.lang.String seqNo) {
		set("seqNo", seqNo);
	}
	
	public java.lang.String getSeqNo() {
		return getStr("seqNo");
	}

	public void setSubmitUser(java.lang.String submitUser) {
		set("submitUser", submitUser);
	}
	
	public java.lang.String getSubmitUser() {
		return getStr("submitUser");
	}

	public void setSubmitDate(java.lang.String submitDate) {
		set("submitDate", submitDate);
	}
	
	public java.lang.String getSubmitDate() {
		return getStr("submitDate");
	}

	public void setSubmitAmt(java.math.BigDecimal submitAmt) {
		set("submitAmt", submitAmt);
	}
	
	public java.math.BigDecimal getSubmitAmt() {
		return get("submitAmt");
	}

	public void setSubmitRemark(java.lang.String submitRemark) {
		set("submitRemark", submitRemark);
	}
	
	public java.lang.String getSubmitRemark() {
		return getStr("submitRemark");
	}

	public void setStartDate(java.lang.String startDate) {
		set("startDate", startDate);
	}
	
	public java.lang.String getStartDate() {
		return getStr("startDate");
	}

	public void setApprover(java.lang.String approver) {
		set("approver", approver);
	}
	
	public java.lang.String getApprover() {
		return getStr("approver");
	}

	public void setApproverComment(java.lang.String approverComment) {
		set("approverComment", approverComment);
	}
	
	public java.lang.String getApproverComment() {
		return getStr("approverComment");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setEndTime(java.lang.String endTime) {
		set("endTime", endTime);
	}
	
	public java.lang.String getEndTime() {
		return getStr("endTime");
	}

}
