package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBomItem<M extends BaseBomItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBomId(java.lang.String bomId) {
		set("bom_id", bomId);
	}
	
	public java.lang.String getBomId() {
		return getStr("bom_id");
	}

	public void setSeqNum(java.lang.String seqNum) {
		set("seq_num", seqNum);
	}
	
	public java.lang.String getSeqNum() {
		return getStr("seq_num");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

	public void setPartNum(java.lang.String partNum) {
		set("part_num", partNum);
	}
	
	public java.lang.String getPartNum() {
		return getStr("part_num");
	}

	public void setPartVersion(java.lang.String partVersion) {
		set("part_version", partVersion);
	}
	
	public java.lang.String getPartVersion() {
		return getStr("part_version");
	}

	public void setPartName(java.lang.String partName) {
		set("part_name", partName);
	}
	
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	public void setPartFamily(java.lang.String partFamily) {
		set("part_family", partFamily);
	}
	
	public java.lang.String getPartFamily() {
		return getStr("part_family");
	}

	public void setPartNameZh(java.lang.String partNameZh) {
		set("part_name_zh", partNameZh);
	}
	
	public java.lang.String getPartNameZh() {
		return getStr("part_name_zh");
	}

}
