package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWkFormDemo<M extends BaseWkFormDemo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setBizUnit(java.lang.String bizUnit) {
		set("bizUnit", bizUnit);
	}
	
	public java.lang.String getBizUnit() {
		return getStr("bizUnit");
	}

	public void setBizType(java.lang.String bizType) {
		set("bizType", bizType);
	}
	
	public java.lang.String getBizType() {
		return getStr("bizType");
	}

	public void setBizNum(java.lang.String bizNum) {
		set("bizNum", bizNum);
	}
	
	public java.lang.String getBizNum() {
		return getStr("bizNum");
	}

	public void setAcctGroup(java.lang.String acctGroup) {
		set("acctGroup", acctGroup);
	}
	
	public java.lang.String getAcctGroup() {
		return getStr("acctGroup");
	}

	public void setProjectCode(java.lang.String projectCode) {
		set("projectCode", projectCode);
	}
	
	public java.lang.String getProjectCode() {
		return getStr("projectCode");
	}

	public void setBizAttr1(java.lang.String bizAttr1) {
		set("bizAttr1", bizAttr1);
	}
	
	public java.lang.String getBizAttr1() {
		return getStr("bizAttr1");
	}

	public void setBizAttr2(java.lang.String bizAttr2) {
		set("bizAttr2", bizAttr2);
	}
	
	public java.lang.String getBizAttr2() {
		return getStr("bizAttr2");
	}

	public void setBizAttr3(java.lang.String bizAttr3) {
		set("bizAttr3", bizAttr3);
	}
	
	public java.lang.String getBizAttr3() {
		return getStr("bizAttr3");
	}

	public void setBizAmt(java.math.BigDecimal bizAmt) {
		set("bizAmt", bizAmt);
	}
	
	public java.math.BigDecimal getBizAmt() {
		return get("bizAmt");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}
	
	public java.lang.String getCreateUser() {
		return getStr("createUser");
	}

	public void setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
	}
	
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	public void setUpdateUser(java.lang.String updateUser) {
		set("updateUser", updateUser);
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("updateUser");
	}

	public void setUpdateDate(java.lang.String updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.lang.String getUpdateDate() {
		return getStr("updateDate");
	}

	public void setSubmitUser(java.lang.String submitUser) {
		set("submitUser", submitUser);
	}
	
	public java.lang.String getSubmitUser() {
		return getStr("submitUser");
	}

	public void setSubmitDate(java.lang.String submitDate) {
		set("submitDate", submitDate);
	}
	
	public java.lang.String getSubmitDate() {
		return getStr("submitDate");
	}

	public void setWkInsNum(java.lang.String wkInsNum) {
		set("wkInsNum", wkInsNum);
	}
	
	public java.lang.String getWkInsNum() {
		return getStr("wkInsNum");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
