package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePoHead<M extends BasePoHead<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderNum(java.lang.String orderNum) {
		set("orderNum", orderNum);
	}
	
	public java.lang.String getOrderNum() {
		return getStr("orderNum");
	}

	public void setVendorCode(java.lang.String vendorCode) {
		set("vendorCode", vendorCode);
	}
	
	public java.lang.String getVendorCode() {
		return getStr("vendorCode");
	}

	public void setVendorName(java.lang.String vendorName) {
		set("vendorName", vendorName);
	}
	
	public java.lang.String getVendorName() {
		return getStr("vendorName");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

}
