package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWkType<M extends BaseWkType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setActionKey(java.lang.String actionKey) {
		set("actionKey", actionKey);
	}
	
	public java.lang.String getActionKey() {
		return getStr("actionKey");
	}

	public void setSeqNo(java.lang.String seqNo) {
		set("seqNo", seqNo);
	}
	
	public java.lang.String getSeqNo() {
		return getStr("seqNo");
	}

	public void setIsAmt(java.lang.Integer isAmt) {
		set("isAmt", isAmt);
	}
	
	public java.lang.Integer getIsAmt() {
		return getInt("isAmt");
	}

	public void setLowAmt(java.lang.Integer lowAmt) {
		set("lowAmt", lowAmt);
	}
	
	public java.lang.Integer getLowAmt() {
		return getInt("lowAmt");
	}

	public void setParamType(java.lang.String paramType) {
		set("paramType", paramType);
	}
	
	public java.lang.String getParamType() {
		return getStr("paramType");
	}

	public void setCalcRule(java.lang.String calcRule) {
		set("calcRule", calcRule);
	}
	
	public java.lang.String getCalcRule() {
		return getStr("calcRule");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
