package com.demo.matanalysis;

import com.demo.model.base.BaseBomItem;

/**
 * Generated by JFinal.
 */
public class BomItem extends BaseBomItem<BomItem> {
    private static final long serialVersionUID = 7181603680123735430L;
    private Double levelRate;

    public Double getLevelRate() {
        return levelRate;
    }

    public void setLevelRate(Double levelRate) {
        this.levelRate = levelRate;
    }
}
