package com.demo.matanalysis;

import com.demo.model.base.BaseBomProjectMapping;

/**
 * Generated by JFinal.
 */
public class BomProjectMapping extends BaseBomProjectMapping<BomProjectMapping> {
	
}
