package com.demo.model;

import com.demo.matanalysis.BomItem;
import com.demo.matanalysis.BomProjectMapping;
import com.demo.matanalysis.PoHead;
import com.demo.matanalysis.PoItem;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("bom_item", "idbom_items", BomItem.class);
		arp.addMapping("bom_project_mapping", "id", BomProjectMapping.class);
		arp.addMapping("po_head", "id", PoHead.class);
		arp.addMapping("po_item", "id", PoItem.class);
		arp.addMapping("user", "id", User.class);
	}
}

