package com.demo.model;

import com.demo.model.base.BaseBomItem;

/**
 * Generated by JFinal.
 */
public class BomItem extends BaseBomItem<BomItem> {
    private static final long serialVersionUID = 7181603680123735430L;

    /**
     * 非数据库字段，手工增加出的字段，用以记录层级比例；
     */
    private Double levelRate;

    public Double getLevelRate() {
        return levelRate;
    }

    public void setLevelRate(Double levelRate) {
        this.levelRate = levelRate;
    }
}
