package com.demo.model;

import com.demo.model.base.BaseBomProjectMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BomProjectMapping extends BaseBomProjectMapping<BomProjectMapping> {
	
}
