package com.demo.model;

import com.demo.model.base.BaseBomProjectMapping;

/**
 * Generated by JFinal.
 */
public class BomProjectMapping extends BaseBomProjectMapping<BomProjectMapping> {

    private static final long serialVersionUID = 3229421123483065917L;
}
