package com.demo.model;

import com.demo.model.base.BasePoHead;

/**
 * Generated by JFinal.
 */
public class PoHead extends BasePoHead<PoHead> {

    private static final long serialVersionUID = 6164766098801517001L;
}
