package com.demo.model;

import com.demo.model.base.BasePoItem;

/**
 * Generated by JFinal.
 */
public class PoItem extends BasePoItem<PoItem> {

    private static final long serialVersionUID = 3490019844629686300L;
}
