package com.demo.model;

import com.demo.model.base.BaseRegionSalesStats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RegionSalesStats extends BaseRegionSalesStats<RegionSalesStats> {
	
}
