package com.demo.model;

import com.demo.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
public class User extends BaseUser<User> {

    public User removeSensitiveInfo() {
        remove("password", "salt");
        return this;
    }
	
}
