package com.demo.model;

import com.demo.model.base.BaseWkFormDemo;
import com.demo.workflow.IFlowTx;

/**
 * Generated by JFinal.
 */
public class WkFormDemo extends BaseWkFormDemo<WkFormDemo> implements IFlowTx {

}
