package com.demo.model;

import com.demo.model.base.BaseWkInstanceStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WkInstanceStep extends BaseWkInstanceStep<WkInstanceStep> {
	
}
